services:
  backend-app:
    build: .
    container_name: sar-backend-app-service
    restart: always
    # [Final Fix] Add the ports mapping to expose the service to the host machine.
    ports:
      - "0.0.1:8000"
    volumes:
      - "${USERPROFILE}/.config/earthengine:/root/.config/earthengine"
    expose:
      - "8000"

  ngrok:
    image: ngrok/ngrok:latest
    container_name: sar-ngrok-service
    restart: always
    ports:
      - "4040:4040"
    depends_on:
      - backend-app
    environment:
      - NGROK_AUTHTOKEN=${NGROK_AUTHTOKEN}
    command: 'http backend-app:8000 --response-header-add "Access-Control-Allow-Origin: *"'