services:
  backend-app:
    build: .
    container_name: sar-backend-ultimate
    restart: always
    ports:
      - "8000:8000" # We expose the port for local testing
      - "4040:4040" # We expose the ngrok UI
    volumes:
      - "${USERPROFILE}/.config/earthengine:/root/.config/earthengine"
    environment:
      # This will read your NGROK_AUTHTOKEN from the .env file
      - NGROK_AUTHTOKEN=${NGROK_AUTHTOKEN}