services:
  backend-app:
    build: .
    container_name: sar-backend-ultimate-host
    restart: always
    # [V15 Ultimate Fix] Use the host's network directly.
    # This is the most robust solution for pyngrok on Docker for Windows.
    network_mode: "host"
    volumes:
      - "${USERPROFILE}/.config/earthengine:/root/.config/earthengine"
    environment:
      # This will read your NGROK_AUTHTOKEN from the .env file
      - NGROK_AUTHTOKEN=${NGROK_AUTHTOKEN}