services:
  backend-app:
    build: .
    container_name: sar-backend-app-service
    restart: always
    volumes:
      - "${USERPROFILE}/.config/earthengine:/root/.config/earthengine"
    environment:
      # We will allow any origin for simplicity in the final version
      - VERCEL_URL=* 

  ngrok:
    image: ngrok/ngrok:latest
    container_name: sar-ngrok-service
    restart: always
    ports:
      - "4040:4040"
    depends_on:
      - backend-app
    environment:
      - NGROK_AUTHTOKEN=${NGROK_AUTHTOKEN}
    # [V11 Final Fix] REMOVE the --domain parameter completely.
    # This command simply creates a tunnel for the backend service.
    command: http backend-app:8000