services:
  backend-app:
    build: .
    container_name: sar-backend-ultimate
    restart: always
    ports:
      - "8000:8000"
      - "4040:4040"
    volumes:
      - "${USERPROFILE}/.config/earthengine:/root/.config/earthengine"
    environment:
      - NGROK_AUTHTOKEN=${NGROK_AUTHTOKEN}
    # [V15 Final Fix] Explicitly set a public DNS server for the container.
    # This bypasses any potential DNS resolution issues within the Docker network.
    dns:
      - 8.8.8.8