services:
  backend-app:
    build: .
    container_name: sar-backend-app-service
    restart: always
    volumes:
      - "${USERPROFILE}/.config/earthengine:/root/.config/earthengine"
    # No need for VERCEL_URL environment variable anymore
    expose:
      - "8000"

  ngrok:
    image: ngrok/ngrok:latest
    container_name: sar-ngrok-service
    restart: always
    ports:
      - "4040:4040"
    depends_on:
      - backend-app
    environment:
      - NGROK_AUTHTOKEN=${NGROK_AUTHTOKEN}
    # [V12 Final Fix] Use ngrok's powerful header modification feature.
    # This command tells ngrok to forcefully add the CORS header to every response.
    # We allow ANY origin ('*') for simplicity during the hackathon.
    command: 'http backend-app:8000 --response-header-add "Access-Control-Allow-Origin: *"'