services:
  backend-app:
    build: .
    container_name: sar-backend-app-service
    restart: always
    ports:
      - "8000:8000" # Expose port 8000 to the host machine
    volumes:
      - "${USERPROFILE}/.config/earthengine:/root/.config/earthengine"
    environment:
      - VERCEL_URL=${VERCEL_URL}