version: '3.8'

services:
  backend-app:
    build: .
    container_name: sar-backend-app-service
    restart: always
    volumes:
      - "%UserProfile%\\.config\\earthengine:/root/.config/earthengine" # For Windows CMD/Powershell
      # For macOS/Linux, use:
      # - "~/.config/earthengine:/root/.config/earthengine"
    environment:
      # This will read the VERCEL_URL from the .env file
      - VERCEL_URL=${VERCEL_URL}

  ngrok:
    image: ngrok/ngrok:latest
    container_name: sar-ngrok-service
    restart: always
    ports:
      - "4040:4040" # Exposes the ngrok web interface for debugging
    depends_on:
      - backend-app
    environment:
      # These will read the secrets from the .env file
      - NGROK_AUTHTOKEN=${NGROK_AUTHTOKEN}
    command: http backend-app:8000 --domain ${NGROK_STATIC_DOMAIN}